
visited = [False] * 7
print(visited)
reseau.listBusStop
reseau.listBusStop.nom
for i in reseau.listBusStop: print(i.nom)
for i in reseau.listBusStop: print(i.name)
print({vertex: inf for vertex in reseau.listBusStop})
print({vertex: 0 for vertex in reseau.listBusStop})
print(float("inf"))
print(inf)
print({vertex: float("inf") for vertex in reseau.listBusStop})
print({vertex: None for vertex in reseau.listBusStop})
runfile('E:/Cours/Semestre 6/Proj-631-Sibra/Reseau.py', wdir='E:/Cours/Semestre 6/Proj-631-Sibra')
runfile('E:/Cours/Semestre 6/Proj-631-Sibra/Index.py', wdir='E:/Cours/Semestre 6/Proj-631-Sibra')
print({busStop: float("inf") for busStop in reseau.listBusStop})
reseau.sensBus(reseau.listBusStop[2], reseau.listBusStop[1])
reseau.sensBus(reseau.listBusStop[2], reseau.listBusStop[3])
runfile('E:/Cours/Semestre 6/Proj-631-Sibra/Index.py', wdir='E:/Cours/Semestre 6/Proj-631-Sibra')
reseau.sensBus(reseau.listBusStop[2], reseau.listBusStop[1])
reseau.sensBus(reseau.listBusStop[2], reseau.listBusStop[3])
reseau.sensBus(reseau.listBusStop[2], reseau.listBusStop[4])
reseau.sensBus(reseau.listBusStop[2], reseau.listBusStop[5])
runfile('E:/Cours/Semestre 6/Proj-631-Sibra/Index.py', wdir='E:/Cours/Semestre 6/Proj-631-Sibra')
reseau.sensBus(reseau.listBusStop[2], reseau.listBusStop[5])
reseau.sensBus(reseau.listBusStop[2], reseau.listBusStop[3])
reseau.sensBus(reseau.listBusStop[2], reseau.listBusStop[1])
reseau.listBusStop[2]
reseau.listBusStop[2].idLigne
reseau.listBusStop[2].idLignes
reseau.listBusStop[20].idLignes
runfile('E:/Cours/Semestre 6/Proj-631-Sibra/Horaire.py', wdir='E:/Cours/Semestre 6/Proj-631-Sibra')
runfile('E:/Cours/Semestre 6/Proj-631-Sibra/Index.py', wdir='E:/Cours/Semestre 6/Proj-631-Sibra')
reseau.getLigneId(reseau.listBusStop[6], reseau.listBusStop[17])
reseau.getLigneId(reseau.listBusStop[6], reseau.listBusStop[7])
reseau.getLigneId(reseau.listBusStop[6], reseau.listBusStop[5])
reseau.getLigneId(reseau.listBusStop[4], reseau.listBusStop[5])
runfile('E:/Cours/Semestre 6/Proj-631-Sibra/Index.py', wdir='E:/Cours/Semestre 6/Proj-631-Sibra')
runfile('E:/Cours/Semestre 6/Proj-631-Sibra/Reseau.py', wdir='E:/Cours/Semestre 6/Proj-631-Sibra')
runfile('E:/Cours/Semestre 6/Proj-631-Sibra/Index.py', wdir='E:/Cours/Semestre 6/Proj-631-Sibra')
debugfile('E:/Cours/Semestre 6/Proj-631-Sibra/Index.py', wdir='E:/Cours/Semestre 6/Proj-631-Sibra')
debugfile('E:/Cours/Semestre 6/Proj-631-Sibra/Reseau.py', wdir='E:/Cours/Semestre 6/Proj-631-Sibra')
runfile('E:/Cours/Semestre 6/Proj-631-Sibra/Reseau.py', wdir='E:/Cours/Semestre 6/Proj-631-Sibra')
debugfile('E:/Cours/Semestre 6/Proj-631-Sibra/Index.py', wdir='E:/Cours/Semestre 6/Proj-631-Sibra')
runfile('E:/Cours/Semestre 6/Proj-631-Sibra/Reseau.py', wdir='E:/Cours/Semestre 6/Proj-631-Sibra')
runfile('E:/Cours/Semestre 6/Proj-631-Sibra/Index.py', wdir='E:/Cours/Semestre 6/Proj-631-Sibra')
debugfile('E:/Cours/Semestre 6/Proj-631-Sibra/Reseau.py', wdir='E:/Cours/Semestre 6/Proj-631-Sibra')
runfile('E:/Cours/Semestre 6/Proj-631-Sibra/Index.py', wdir='E:/Cours/Semestre 6/Proj-631-Sibra')
debugfile('E:/Cours/Semestre 6/Proj-631-Sibra/Index.py', wdir='E:/Cours/Semestre 6/Proj-631-Sibra')
runfile('E:/Cours/Semestre 6/Proj-631-Sibra/Index.py', wdir='E:/Cours/Semestre 6/Proj-631-Sibra')
debugfile('E:/Cours/Semestre 6/Proj-631-Sibra/Index.py', wdir='E:/Cours/Semestre 6/Proj-631-Sibra')
runfile('E:/Cours/Semestre 6/Proj-631-Sibra/Index.py', wdir='E:/Cours/Semestre 6/Proj-631-Sibra')
runfile('E:/Cours/Semestre 6/Proj-631-Sibra/Reseau.py', wdir='E:/Cours/Semestre 6/Proj-631-Sibra')
runfile('E:/Cours/Semestre 6/Proj-631-Sibra/Index.py', wdir='E:/Cours/Semestre 6/Proj-631-Sibra')